### ISSUE TITLE
V2 Support?

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [almonds0166/pk.py#19]
Heya, is V2 support still planned? It's been out for quite a while now haha

**Comment by almonds0166** [comment]
Yeah, sorry, been busy, and just got home from a trip. I'll pick it back up after breakfast today, cheers!

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Ah okay, thanks! I'll close this issue now haha
