### ISSUE TITLE
Privacy being null in the api response errors

### ISSUE THREAD

**Issue by FractalGeodes** [almonds0166/pk.py#21]
Was trying to test fetching a system other than the token's one so that I didn't have to go add a banner to our own to test something and realised that if the api response returns `null` for the privacy then the library fails to construct the system, presumably because it is assumed that the privacy will always be a dictionary when in reality it can be null

```
│ /home/ringlings/Documents/PluralSnug/venv/lib/python3.10/site-packages/plura │
│ lkit/v2/models.py:783 in __init__                                            │
│                                                                              │
│    780 │   │   Model.__init__(self, json, ignore_keys)                       │
│    781 │   │   # fix up the remaining keys                                   │
│    782 │   │   self.id = SystemId(id=json["id"], uuid=json["uuid"])          │
│ ❱  783 │   │   for key, value in json["privacy"].items():                    │
│    784 │   │   │   self.__dict__[key] = Privacy(value)                       │
│    785                                                                       │
│    786 class Group(Model):                                                   │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'items'
```

I'm not sure if there's any way around this but it seems like an oversight that should have attention brought to it

**Comment by almonds0166** [comment]
Thank you to bringing this up, I'll patch this as soon as I can

**Comment by almonds0166** [comment]
I've determined the origin and nature of the error and was able to fix related bugs, and it gave me the push to implement long-planned changes.

Can you `pip install -U pluralkit` (for v1.1.0) and confirm that your error is gone?

**Comment by FractalGeodes** [comment]
Done that, got a new error now:
`ValueError: None is not a valid Privacy`
```
│ /home/ringlings/Documents/PluralSnug/venv/lib/python3.10/site-packages/pluralkit/v2/models.py:80 │
│ 7 in __init__                                                                                    │
│                                                                                                  │
│    804 │   │   # incorporate privacy keys when given                                             │
│    805 │   │   if json.get("privacy") is not None:                                               │
│    806 │   │   │   for key, value in json["privacy"].items():                                    │
│ ❱  807 │   │   │   │   self.__dict__[key] = Privacy(value)                                       │
│    808 │   │   else:                                                                             │
│    809 │   │   │   for key, _ in self.__class__.__annotations__.items():                         │
│    810 │   │   │   │   if "privacy" in key:                                                      │
```

(The rest of the stacktrace is in the enum class and I can grab them if you need)

**Comment by almonds0166** [comment]
Huh, that suggests that the API is returning null values, which I would not expect given my understanding of the development behind the API.

At a high level, what are you trying to do? I've experimented with fetching my system and a member from that system, with or without my token, and I haven't encountered that error. I'm guessing you're doing something else?

Edit: Oh, right, fetching another system that's not your own, I'll look into it

**Comment by almonds0166** [comment]
I tried with other systems and couldn't reproduce it. Are you able to fetch _any_ systems? That is, can you tell if this error is rare? I'd appreciate it if you can do some scouting and see if this is associated with specific system attributes.

My only guess is that some systems have old `null` values for some privacy fields, which was deprecated a few years ago.

Anyway, I added some ` if value is not None else None` bits, and v1.1.1 should be ready for `null` privacy fields.

If errors continue, please let me know anything particular about your setup that may be relevant.

**Comment by FractalGeodes** [comment]
The specific line I was using to fetch the system is `client.get_system(SystemId("exmpl"))` (generating a system id for the example system and then fetching it)
Changing the ID we fetched to any system that isn't our own still errors, although I'm not sure if it's an issue with specific privacy settings because I don't have a list of IDs to check

The client has async mode off but other than that I believe that would be the only non-default thing about the environment

**Comment by almonds0166** [comment]
So, when you run this:

```py
from pluralkit import Client, SystemId

# set up client
client = Client(async_mode=False)

# get example system
system_id = SystemId("exmpl")
system = client.get_system(system_id)

# print system info
for key, value in system.__dict__.items():
   print(key, "->", value)
```

You're _still_ getting an error? To be clear, I cannot reproduce an error with this script in a fresh venv.

If the example system _does_ work for you, but your other systems don't, would you be willing to DM me the IDs over Discord for the sake of their privacy?

**Comment by FractalGeodes** [comment]
After looking at it a little bit more, I think the problem is actually on our end, sorry
Other than that, this looks to be fixed
