### ISSUE TITLE
`Switch.json()` returns `MemberId` objects instead of strings of their IDs

### ISSUE THREAD

**Issue by FractalGeodes** [almonds0166/pk.py#22]
hi its us again :catresort:

We were messing around with storing json formatted switch data in a cache file, and we were specifically attempting to `json.dump()` them as it seemed like the easiest solution for it. But we ran into an issue:

```py
import pluralkit
import json

pk = pluralkit.Client(async_mode=False)

switch = pk.get_switches("exmpl", limit=1)[0]

switch_json = switch.json()

print(switch_json)
# > {... 'members': [MemberId('loxqc'), MemberId('gaznz')]}

json.dumps(switch_json)
# > TypeError: Object of type MemberId is not JSON serializable
```

The member IDs (which should be strings in this case) are `MemberId` objects, and the json library spits them back out because it can't process them.

I believe this is because `Model.json()` recursively checks if objects have a json attribute, and stops if not (to avoid trying to convert non-pk objects)
The members in a switch from `get_switches` are stored in a list, which doesn't have a json function, so the library skips over them believing it's reached the bottom of the tree.

I'm unsure how this could be solved, but it feels like a bug that should probably be reported.

**Comment by almonds0166** [comment]
Thanks for bringing this to our attention! And thanks for providing an example script I can play with.

What you said makes perfect sense to me. The `json` methods were originally placed there just to make things easier in the backend. I agree it's desirable to get this working at a finer level, namely for lists. I'll look into this soon(tm).

**Comment by almonds0166** [comment]
Should be fixed! It should handle lists, sets, tuples, and dicts now, if those extra types might ever happen to occur. Please close the issue after confirming -> `pip install -U pluralkit`

**Comment by FractalGeodes** [comment]
Tested the example code I gave and it works after updating, thanks!
We eventually ended up realizing that the way we were doing things in our main script was inefficient and ended up naturally moving away from this being a problem in the first place, but a bug fixed is a bug fixed.
